# Generated by Django 5.1.4 on 2025-01-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovegram', '0002_message_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_files/'),
        ),
    ]
