# Generated by Django 5.1.4 on 2025-01-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovegram', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'ارسال\u200cشده'), ('read', 'خوانده\u200cشده')], default='sent', max_length=20),
        ),
    ]
