# Generated by Django 5.1.4 on 2025-01-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovegram', '0011_user_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
